// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using copilot_sample.DataAccess;

#nullable disable

namespace copilotsample.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250611184540_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ParentCategoryID");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "Electronic gadgets and devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "Portable computers",
                            Name = "Laptops",
                            ParentCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Mobile phones and accessories",
                            Name = "Smartphones",
                            ParentCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Electronics accessories",
                            Name = "Accessories",
                            ParentCategoryID = 1
                        });
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("InventoryID");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("LastUpdated")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.HasKey("InventoryID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            InventoryID = 1,
                            LastUpdated = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductID = 1,
                            Quantity = 25
                        },
                        new
                        {
                            InventoryID = 2,
                            LastUpdated = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductID = 2,
                            Quantity = 10
                        },
                        new
                        {
                            InventoryID = 3,
                            LastUpdated = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductID = 3,
                            Quantity = 50
                        },
                        new
                        {
                            InventoryID = 4,
                            LastUpdated = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductID = 4,
                            Quantity = 100
                        },
                        new
                        {
                            InventoryID = 5,
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductID = 5,
                            Quantity = 30
                        },
                        new
                        {
                            InventoryID = 6,
                            LastUpdated = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductID = 6,
                            Quantity = 45
                        },
                        new
                        {
                            InventoryID = 7,
                            LastUpdated = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductID = 7,
                            Quantity = 200
                        });
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Brand");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("SKU");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Brand = "TechBrand",
                            CategoryID = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight business laptop with high performance",
                            IsActive = true,
                            Name = "UltraBook X1",
                            SKU = "SKU-UBX1",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 2,
                            Brand = "GamePro",
                            CategoryID = 2,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-end gaming laptop with RGB lighting",
                            IsActive = true,
                            Name = "Gaming Beast Z9",
                            SKU = "SKU-GBZ9",
                            UpdatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 3,
                            Brand = "SmartTech",
                            CategoryID = 3,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest smartphone with AI-powered camera",
                            IsActive = true,
                            Name = "Galaxy X10",
                            SKU = "SKU-GX10",
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 4,
                            Brand = "SoundWave",
                            CategoryID = 4,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless earphones with noise cancellation",
                            IsActive = true,
                            Name = "EarPods Pro",
                            SKU = "SKU-EPP",
                            UpdatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 5,
                            Brand = "ThinkCorp",
                            CategoryID = 2,
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable business laptop with excellent battery life",
                            IsActive = true,
                            Name = "ThinkMate Pro 14",
                            SKU = "SKU-TMP14",
                            UpdatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 6,
                            Brand = "PixelTech",
                            CategoryID = 3,
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact smartphone with high-resolution camera",
                            IsActive = true,
                            Name = "PixelCam A2",
                            SKU = "SKU-PXA2",
                            UpdatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 7,
                            Brand = "ChargeX",
                            CategoryID = 4,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable power bank with fast charging support",
                            IsActive = true,
                            Name = "PowerCharge 10000",
                            SKU = "SKU-PC10000",
                            UpdatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.ProductAttribute", b =>
                {
                    b.Property<int>("AttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("AttributeID");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("AttributeName");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("AttributeValue");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.HasKey("AttributeID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductAttributes", (string)null);

                    b.HasData(
                        new
                        {
                            AttributeID = 1,
                            AttributeName = "Processor",
                            AttributeValue = "Intel Core i7",
                            ProductID = 1
                        },
                        new
                        {
                            AttributeID = 2,
                            AttributeName = "RAM",
                            AttributeValue = "16GB",
                            ProductID = 1
                        },
                        new
                        {
                            AttributeID = 3,
                            AttributeName = "Storage",
                            AttributeValue = "512GB SSD",
                            ProductID = 1
                        },
                        new
                        {
                            AttributeID = 4,
                            AttributeName = "Processor",
                            AttributeValue = "AMD Ryzen 9",
                            ProductID = 2
                        },
                        new
                        {
                            AttributeID = 5,
                            AttributeName = "RAM",
                            AttributeValue = "32GB",
                            ProductID = 2
                        },
                        new
                        {
                            AttributeID = 6,
                            AttributeName = "Graphics Card",
                            AttributeValue = "NVIDIA RTX 4080",
                            ProductID = 2
                        },
                        new
                        {
                            AttributeID = 7,
                            AttributeName = "Display",
                            AttributeValue = "6.5-inch OLED",
                            ProductID = 3
                        },
                        new
                        {
                            AttributeID = 8,
                            AttributeName = "Battery",
                            AttributeValue = "4000mAh",
                            ProductID = 3
                        },
                        new
                        {
                            AttributeID = 9,
                            AttributeName = "Camera",
                            AttributeValue = "108MP",
                            ProductID = 3
                        },
                        new
                        {
                            AttributeID = 10,
                            AttributeName = "Connectivity",
                            AttributeValue = "Bluetooth 5.2",
                            ProductID = 4
                        },
                        new
                        {
                            AttributeID = 11,
                            AttributeName = "Noise Cancellation",
                            AttributeValue = "Active",
                            ProductID = 4
                        },
                        new
                        {
                            AttributeID = 12,
                            AttributeName = "Battery Life",
                            AttributeValue = "8 hours",
                            ProductID = 4
                        },
                        new
                        {
                            AttributeID = 13,
                            AttributeName = "Processor",
                            AttributeValue = "Intel i5",
                            ProductID = 5
                        },
                        new
                        {
                            AttributeID = 14,
                            AttributeName = "RAM",
                            AttributeValue = "8GB",
                            ProductID = 5
                        },
                        new
                        {
                            AttributeID = 15,
                            AttributeName = "Weight",
                            AttributeValue = "1.3kg",
                            ProductID = 5
                        },
                        new
                        {
                            AttributeID = 16,
                            AttributeName = "Camera",
                            AttributeValue = "64MP",
                            ProductID = 6
                        },
                        new
                        {
                            AttributeID = 17,
                            AttributeName = "Storage",
                            AttributeValue = "128GB",
                            ProductID = 6
                        },
                        new
                        {
                            AttributeID = 18,
                            AttributeName = "Display",
                            AttributeValue = "6.1-inch AMOLED",
                            ProductID = 6
                        },
                        new
                        {
                            AttributeID = 19,
                            AttributeName = "Capacity",
                            AttributeValue = "10000mAh",
                            ProductID = 7
                        },
                        new
                        {
                            AttributeID = 20,
                            AttributeName = "USB Ports",
                            AttributeValue = "2",
                            ProductID = 7
                        },
                        new
                        {
                            AttributeID = 21,
                            AttributeName = "Fast Charging",
                            AttributeValue = "Yes",
                            ProductID = 7
                        });
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.ProductPrice", b =>
                {
                    b.Property<int>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriceID");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("USD")
                        .HasColumnName("CurrencyCode");

                    b.Property<DateTime>("EffectiveFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("EffectiveFrom")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("EffectiveTill")
                        .HasColumnType("TEXT")
                        .HasColumnName("EffectiveTill");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.HasKey("PriceID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductPrices", (string)null);

                    b.HasData(
                        new
                        {
                            PriceID = 1,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1299.99m,
                            ProductID = 1
                        },
                        new
                        {
                            PriceID = 2,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTill = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1199.99m,
                            ProductID = 1
                        },
                        new
                        {
                            PriceID = 3,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1999.00m,
                            ProductID = 2
                        },
                        new
                        {
                            PriceID = 4,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 899.50m,
                            ProductID = 3
                        },
                        new
                        {
                            PriceID = 5,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 199.99m,
                            ProductID = 4
                        },
                        new
                        {
                            PriceID = 6,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 999.99m,
                            ProductID = 5
                        },
                        new
                        {
                            PriceID = 7,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 649.00m,
                            ProductID = 6
                        },
                        new
                        {
                            PriceID = 8,
                            CurrencyCode = "USD",
                            EffectiveFrom = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 49.99m,
                            ProductID = 7
                        });
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.ProductReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReviewID");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("Comment");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductID");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Rating");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReviewDate")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ReviewerName");

                    b.HasKey("ReviewID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductReviews_Rating", "Rating BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            Comment = "Absolutely love this laptop! Fast and sleek.",
                            ProductID = 1,
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Alice Johnson"
                        },
                        new
                        {
                            ReviewID = 2,
                            Comment = "Good performance but gets a bit warm.",
                            ProductID = 1,
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Bob Smith"
                        },
                        new
                        {
                            ReviewID = 3,
                            Comment = "A beast for gaming. Smooth experience!",
                            ProductID = 2,
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Tommy Lee"
                        },
                        new
                        {
                            ReviewID = 4,
                            Comment = "Amazing camera and display! Worth every penny.",
                            ProductID = 3,
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Carlos Vega"
                        },
                        new
                        {
                            ReviewID = 5,
                            Comment = "Battery life could be better.",
                            ProductID = 3,
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Diana Lee"
                        },
                        new
                        {
                            ReviewID = 6,
                            Comment = "Very comfortable fit and great sound.",
                            ProductID = 4,
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Emma Stone"
                        },
                        new
                        {
                            ReviewID = 7,
                            Comment = "Connection drops sometimes.",
                            ProductID = 4,
                            Rating = 2,
                            ReviewDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "John Doe"
                        },
                        new
                        {
                            ReviewID = 8,
                            Comment = "Reliable laptop, solid build and decent performance.",
                            ProductID = 5,
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Harvey Dent"
                        },
                        new
                        {
                            ReviewID = 9,
                            Comment = "Good for light work, but a bit slow for multitasking.",
                            ProductID = 5,
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Rachel Green"
                        },
                        new
                        {
                            ReviewID = 10,
                            Comment = "Compact yet powerful. Great value for the price.",
                            ProductID = 6,
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Bruce Banner"
                        },
                        new
                        {
                            ReviewID = 11,
                            Comment = "Excellent camera quality and battery.",
                            ProductID = 6,
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Natasha Romanoff"
                        },
                        new
                        {
                            ReviewID = 12,
                            Comment = "Lasts all day. Perfect for travel.",
                            ProductID = 7,
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Steve Rogers"
                        },
                        new
                        {
                            ReviewID = 13,
                            Comment = "Charges fast, but gets warm during use.",
                            ProductID = 7,
                            Rating = 3,
                            ReviewDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewerName = "Tony Stark"
                        });
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Category", b =>
                {
                    b.HasOne("copilot_sample.DataAccess.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Inventory", b =>
                {
                    b.HasOne("copilot_sample.DataAccess.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("copilot_sample.DataAccess.Entities.Inventory", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Product", b =>
                {
                    b.HasOne("copilot_sample.DataAccess.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.ProductAttribute", b =>
                {
                    b.HasOne("copilot_sample.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.ProductPrice", b =>
                {
                    b.HasOne("copilot_sample.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.ProductReview", b =>
                {
                    b.HasOne("copilot_sample.DataAccess.Entities.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("copilot_sample.DataAccess.Entities.Product", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductPrices");

                    b.Navigation("ProductReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
